<a href="https://colab.research.google.com/github/Shivkumar-777/Edu-Python/blob/main/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

ec = [1200, 3400, 2900, 1800, 2500]
energy_consumption = np.array(ec)

print("Energy Consumption (in MWH) for different Renewable Sources : ")
print(energy_consumption)



Energy Consumption (in MWH) for different Renewable Sources : 
[1200 3400 2900 1800 2500]


In [3]:
import numpy as np

In [4]:
A = np.ones(4)
A2 = np.ones((2, 2))
print(A)
print("\n" ,A2)

[1. 1. 1. 1.]

 [[1. 1.]
 [1. 1.]]


In [5]:
M = np.zeros(4)
print(M)

[0. 0. 0. 0.]


In [6]:
# Identity Matrix

M = np.identity(4)
print(M)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
total_consumption = np.sum(energy_consumption)
print(f"Total Energy Consumption : {total_consumption} MWH")

Total Energy Consumption : 11800 MWH


In [ ]:
# Standard deviation

In [12]:
# Reshaping the array

enenrgy_consumption = np.array([1200, 3400, 2900, 1800, 2500, 1800])

reshaped_energy_consumption = enenrgy_consumption.reshape((3, 2))
print(reshaped_energy_consumption)

[[1200 3400]
 [2900 1800]
 [2500 1800]]


In [13]:
# Flattern

flattened_energy_consumption = enenrgy_consumption.flatten()
print(flattened_energy_consumption)

[1200 3400 2900 1800 2500 1800]


In [14]:
# Transpose

transposed_energy_consumption = enenrgy_consumption.T
print(transposed_energy_consumption)

[1200 3400 2900 1800 2500 1800]


In [15]:
# Resizing The Array

resized_energy_consumption = enenrgy_consumption.resize((2, 3))
print(resized_energy_consumption)



None


In [17]:
np.random.randint(1, 10)

4

In [19]:
np.unique(energy_consumption)

array([1200, 1800, 2500, 2900, 3400])

In [20]:
np.power.reduce(energy_consumption)

np.int64(0)

In [21]:
import pandas as ps

In [22]:
renewable_sources = ["Solar", "Wind", "Hydropower",  "Geothermal", "Biomass"]

data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [24]:
renewable_series = ps.Series(renewable_sources)
print(renewable_series)

0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [25]:
# Adding New Columns/Feature Engineering

renewable_df = ps.DataFrame(data)
print(renewable_df)



              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023  


In [26]:
# Group By Technology and calculate total capacity for each typre

total_capacity_by_technology = renewable_df.groupby("Technology")["Capacity (MW)"].sum()
print(total_capacity_by_technology)


Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64
